Update workflow

diff --git a/.github/workflows/DDR5SPDEditor-action.yml b/.github/workflows/DDR5SPDEditor-action.yml
--- a/.github/workflows/DDR5SPDEditor-action.yml
+++ b/.github/workflows/DDR5SPDEditor-action.yml
@@ -18,13 +18,11 @@ jobs:
     container: ${{ matrix.sys.container }}
 
     strategy:
-      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
       fail-fast: true
-
       matrix:
         sys:
-          - { os: ubuntu-latest , shell: bash           , cxx: g++-13, release_name: DDR5SPDEditor-linux-x86_64-qt6 }
-          - { os: ubuntu-latest , shell: 'alpine.sh {0}', cxx: g++   , release_name: DDR5SPDEditor-linux-x86_64-qt6-alpine }
+          - { os: ubuntu-latest , shell: bash           , cxx: g++-13, release_name: DDR5SPDEditor-linux-x86_64-qt6.tar.gz }
+          - { os: ubuntu-latest , shell: 'alpine.sh {0}', cxx: g++   , release_name: DDR5SPDEditor-linux-x86_64-qt6-alpine.tar.gz }
           - { os: windows-latest, shell: 'msys2 {0}'    , cxx: g++   , release_name: DDR5SPDEditor-win-x86_64-qt6.7z }
         build_type: [Release]
 
@@ -33,19 +31,18 @@ jobs:
         shell: ${{ matrix.sys.shell }}
 
     steps:
-
     - name: Install packages required for the workflow and build deps
       uses: ConorMacBride/install-package@v1
       with:
-        apt: build-essential cmake file gcc make ninja-build pkgconf sudo ${{ env.QT_PACKAGE }}
+        apt: build-essential cmake file gcc make ninja-build pkgconf sudo curl wget ${{ env.QT_PACKAGE }} qt6-tools-dev
       env:
-        QT_PACKAGE: ${{ matrix.sys.os == 'ubuntu-20.04' && 'qt5-default qtbase5-dev qt5-qmake libqt5widgets5 libqt5opengl5 libqt5opengl5-dev libqt5gui5 libgl1-mesa-dev libglvnd-dev' || 'qt6-base-dev qt6-base-dev-tools qmake6 libqt6openglwidgets6 libqt6opengl6 libqt6opengl6-dev libqt6gui6 libgl1-mesa-dev libglvnd-dev' }}
+        QT_PACKAGE: ${{ matrix.sys.os == 'ubuntu-20.04' && 'qt5-default qtbase5-dev qt5-qmake libqt5widgets5 libqt5opengl5 libqt5opengl5-dev libqt5gui5 libgl1-mesa-dev libglvnd-dev' || 'qt6-base-dev qt6-base-private-dev' }}
 
     - name: Install & configure Alpine Linux build environment
       uses: jirutka/setup-alpine@v1
       if: matrix.sys.shell == 'alpine.sh {0}'
       with:
-        packages: build-base cmake curl dialog eudev eudev-dev eudev-libs git libusb-dev linux-headers make ninja-build pkgconf pkgconf-dev py3-pip py3-setuptools python3 samurai sudo wget qt6-qtbase qt6-qtbase-dev qt6-qttools qt6-qttools-dev qt6-qttools-libs mesa mesa-gl mesa-dev
+        packages: build-base cmake curl dialog eudev eudev-dev eudev-libs git libusb-dev linux-headers make ninja-build pkgconf pkgconf-dev py3-pip py3-setuptools python3 samurai sudo wget qt6-qtbase qt6-qtbase-dev qt6-qttools-dev linuxdeployqt
 
     - name: Setup MSYS2 UCRT64
       if: matrix.sys.shell == 'msys2 {0}'
@@ -53,7 +50,7 @@ jobs:
       with:
         msystem: UCRT64
         update: true
-        install: git make mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-qt6-base mingw-w64-ucrt-x86_64-7zip
+        install: git make mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-qt6-base mingw-w64-ucrt-x86_64-qt6-tools mingw-w64-ucrt-x86_64-7zip
         pacboy: cmake:p ninja:p toolchain:p
 
     - name: Setup 'Toolchain test builds' PPA & install GCC 13
@@ -61,7 +58,7 @@ jobs:
       run: |
         sudo add-apt-repository ppa:ubuntu-toolchain-r/test
         sudo apt update
-        sudo apt install gcc-13-base gcc-13 g++-13 libstdc++-13-dev libstdc++6
+        sudo apt install -y gcc-13-base gcc-13 g++-13 libstdc++-13-dev libstdc++6
 
     - name: Checkout repo
       uses: actions/checkout@v4
@@ -78,13 +75,64 @@ jobs:
     - name: Build CMake project
       run: cmake --build build
 
-    - name: Prepare binaries and make Windows archive with libs
+    - name: Install linuxdeployqt (Ubuntu)
+      if: matrix.sys.shell == 'bash'
+      run: |
+        curl -L https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage -o /usr/local/bin/linuxdeployqt
+        chmod +x /usr/local/bin/linuxdeployqt
+
+    - name: Deploy Qt runtime (Windows)
+      if: matrix.sys.shell == 'msys2 {0}'
+      run: |
+        /ucrt64/bin/windeployqt.exe --verbose 2 "build/${{ env.binary_orig }}.exe"
+      env:
+        binary_orig: 'DDR5SPDEditor'
+
+    - name: Deploy Qt runtime (Linux)
+      if: matrix.sys.shell != 'msys2 {0}'
+      run: |
+        # If linuxdeployqt is an AppImage, prefer extracted AppRun to avoid FUSE
+        if [ -x /usr/local/bin/linuxdeployqt ]; then
+          LINUXDEPLOYQT=/usr/local/bin/linuxdeployqt
+        else
+          LINUXDEPLOYQT=$(command -v linuxdeployqt || true)
+        fi
+
+        # Prepare minimal AppDir to satisfy linuxdeployqt
+        mkdir -p build/AppDir/usr/bin build/AppDir/usr/share/applications build/AppDir/usr/share/icons/hicolor/256x256/apps
+        cp build/${{ env.binary_orig }} build/AppDir/usr/bin/${{ env.binary_orig }}
+        cat > build/AppDir/usr/share/applications/${{ env.binary_orig }}.desktop <<'EOF'
+        [Desktop Entry]
+        Type=Application
+        Name=DDR5SPDEditor
+        Exec=DDR5SPDEditor
+        Icon=ddr5spdeditor
+        Categories=Utility;
+        EOF
+        # Optional icon; ignore if missing
+        if [ -f assets/icon.png ]; then cp assets/icon.png build/AppDir/usr/share/icons/hicolor/256x256/apps/ddr5spdeditor.png; fi
+
+        if [ -x "$LINUXDEPLOYQT" ]; then
+          "$LINUXDEPLOYQT" build/AppDir/usr/share/applications/${{ env.binary_orig }}.desktop -bundle-non-qt-libs -verbose=2
+        else
+          echo "linuxdeployqt not found" && exit 1
+        fi
+
+        # Move deployed payload to staging dir
+        mkdir -p dist
+        mv build/AppDir dist/${{ matrix.sys.release_name }}-contents
+      env:
+        binary_orig: 'DDR5SPDEditor'
+
+    - name: Prepare binaries and make archive with libs
       if: matrix.sys.release_name != ''
       run: |
+        mkdir -p dist
         if [[ "${{ env.is_windows_build}}" == "true" ]]; then
-          7z -mx=9 a build/${{ matrix.sys.release_name }} ./build/${{ env.binary_orig }}.exe "/ucrt64/bin/Qt6Core.dll" "/ucrt64/bin/Qt6Widgets.dll" "/ucrt64/bin/Qt6Gui.dll"
+          # Include exe + all Qt runtime pulled in by windeployqt
+          7z -mx=9 a dist/${{ matrix.sys.release_name }} ./build/${{ env.binary_orig }}.exe ./build/*.dll ./build/plugins ./build/translations
         else
-          mv build/${{ env.binary_orig }} build/${{ matrix.sys.release_name }}
+          tar -czf dist/${{ matrix.sys.release_name }} -C dist "${{ matrix.sys.release_name }}-contents"
         fi
       env:
         binary_orig: 'DDR5SPDEditor'
@@ -96,4 +144,4 @@ jobs:
       with:
         fail_on_unmatched_files: false
         generate_release_notes: true        
-        files: build/${{ matrix.sys.release_name }}
+        files: dist/${{ matrix.sys.release_name }}
